# Site settings
title: horia141 -- blog
email: horia141@gmail.com
description: >
  This is my blog. There are many like it, but this one is mine. I write about
  software engineering and computer science topics. The usual suspects, 
  I suppose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://horia141.com"
github_username: horia141
linkedin_username: horia141
stackoverflow_url: http://stackoverflow.com/users/5910563/horia141
stackoverflow_username: horia141
permalink: ":title.html"

# Build settings
markdown: kramdown
